language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 2.5.5
  - 2.6.2
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.6.x
notifications:
  email: true
before_script:
  - nvm install 7
  - npm install mjml
  - npm install promise
