---
name: test
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_manager:
          - npm
          - yarn
        rails_version:
          - "~> 7.0"
          - "~> 6.1"
        ruby_version:
          - "3.1"
          - "3.0"
          - "2.7"
    name: ${{ matrix.package_manager }}, Rails ${{ matrix.rails_version }}, Ruby ${{ matrix.ruby_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install rails dependencies
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Install mjml with npm
        if: ${{ matrix.package_manager == 'npm' }}
        run: npm add mjml
      - name: Install mjml with yarn
        if: ${{ matrix.package_manager == 'yarn' }}
        run: yarn add mjml
      - name: Run tests
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
        run: rake
      - name: Run RuboCop
        run: bundle exec rubocop
